# ~/.config/yazi/yazi.toml

[manager]
# Layout ratio for parent, current, and preview panes
ratio = [1, 4, 3]

# Sorting method: "alphabetical", "natural", "mtime", "size"
sort_by = "natural"

# Case-sensitive sorting
sort_sensitive = false

# Reverse the sorting order
sort_reverse = false

# Directories appear before files
sort_dir_first = true

# Show hidden files
show_hidden = false

[preview]
# Tab size for text previews
tab_size = 2

# Maximum width of the preview pane
max_width = 600

# Maximum height of the preview pane
max_height = 900

[opener]
edit = [
    { run = '${EDITOR:-vi} "$@"', block = true, for = "unix" },
    { run = 'code -w %*', block = true, desc = "Code (block)", for = "windows" },
]
open = [
    { run = 'xdg-open "$1"', for = "linux" },
    { run = 'open "$@"', for = "macos" },
    { run = 'start "" "%1"', for = "windows" },
]
reveal = [
    { run = 'xdg-open "$(dirname "$1")"', for = "linux" },
    { run = 'open -R "$1"', for = "macos" },
    { run = 'explorer /select,"%1"', for = "windows" },
]
